# ============================================================================
# MapleStory Auto Detection — 自定义配置
# ============================================================================

system:
  fps_limit_main: 15

title:
  enable: true                       # 用称号定位角色
  offset: [0, -60]                  # 称号→角色中心偏移 [x,y]，负y=向上

monster_detect:
  monsters: ["black_axe_stump"]
  mode: "color"
  diff_thres: 0.46
  scales: [1]
  display_scale: 0.58
  detection_interval: 2
